# Generated by Django 2.2.5 on 2019-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyname', models.CharField(max_length=10, verbose_name='propertyname')),
                ('Location', models.CharField(max_length=20, verbose_name='location')),
            ],
        ),
    ]
