# Generated by Django 2.2.5 on 2019-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(max_length=100, verbose_name='PropertyName')),
                ('Address', models.CharField(max_length=100, verbose_name='Address')),
                ('Location', models.CharField(max_length=100, verbose_name='Location')),
                ('PhoneNumber', models.CharField(max_length=100, verbose_name='PhoneNumber')),
                ('AgentName', models.CharField(max_length=100, verbose_name='AgentName')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Availability', models.CharField(max_length=100, verbose_name='Availability')),
                ('PropertyType', models.CharField(max_length=100, verbose_name='PropertyType')),
            ],
        ),
    ]
