# Generated by Django 2.2.5 on 2019-12-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyname', models.CharField(max_length=10, verbose_name='propertyname')),
                ('Location', models.CharField(max_length=20, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(max_length=100, verbose_name='PropertyName')),
                ('Address', models.CharField(max_length=100, verbose_name='Address')),
                ('Location', models.CharField(max_length=100, verbose_name='Location')),
                ('PhoneNumber', models.CharField(max_length=100, verbose_name='PhoneNumber')),
                ('AgentName', models.CharField(max_length=100, verbose_name='AgentName')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Availability', models.CharField(max_length=100, verbose_name='Availability')),
                ('PropertyType', models.CharField(max_length=100, verbose_name='PropertyType')),
                ('Price', models.CharField(max_length=100, verbose_name='Price')),
                ('Bed', models.CharField(max_length=100, verbose_name='Bed')),
                ('Bath', models.CharField(max_length=100, verbose_name='Bath')),
                ('Area', models.CharField(max_length=100, verbose_name='Area')),
                ('Pool', models.CharField(max_length=100, verbose_name='Pool')),
                ('DimView', models.CharField(max_length=100, verbose_name='DimView')),
                ('Furnished', models.CharField(max_length=100, verbose_name='Furnished')),
            ],
        ),
    ]
