# Generated by Django 2.2.5 on 2019-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='DimView',
            field=models.CharField(max_length=100, verbose_name='DimView'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
