# Generated by Django 2.2.5 on 2019-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_auto_20191216_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.DeleteModel(
            name='LocEvent',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='AgentName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='DimView',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Furnished',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PhoneNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Pool',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PropertyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PropertyType',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
