# Generated by Django 2.2.5 on 2019-12-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0006_auto_20191216_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PropPublished', models.CharField(max_length=100)),
                ('Sold', models.CharField(max_length=100)),
                ('ProfileStat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Bought', models.CharField(max_length=100)),
                ('ProfileStat', models.CharField(max_length=100)),
                ('LastLogin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='AgentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.Agent'),
        ),
    ]
