# Generated by Django 2.2.5 on 2019-12-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0007_auto_20191228_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='DOB',
        ),
        migrations.AddField(
            model_name='agent',
            name='Gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='Age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='Gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='AgentName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ProfileStat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='PropPublished',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Sold',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Bought',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastLogin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ProfileStat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='AgentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_App.Agent'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Availability',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bath',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='DimView',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Furnished',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Pool',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PropertyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PropertyType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PropertiesSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.CharField(default='', max_length=100)),
                ('AgentName', models.CharField(default='', max_length=100)),
                ('CustomerName', models.CharField(default='', max_length=100)),
                ('Location', models.CharField(default='', max_length=100)),
                ('DateOfSale', models.CharField(default='', max_length=100)),
                ('Email', models.DateField(default='', max_length=100)),
                ('PropID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.Customer')),
            ],
        ),
    ]
