# Generated by Django 2.2.5 on 2019-12-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0009_auto_20191231_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='PhoneNumber',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='agent',
            name='PropPublished',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Sold',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Bought',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Area',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bath',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Bed',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='PhoneNumber',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='Price',
            field=models.IntegerField(default=''),
        ),
    ]
